server:
  port: 8080
  host: localhost

logging:
  level: all
  folder: "./logs"

routes:
  - path: /*
    name: allServer
    strategy: round-robin
    max_nodes: 0
    health_timeout_ms: 5000
    docker:
      image: node-server
      internal_port: 3000
    servers:
    