server:
  port: 8080
  host: localhost

logging:
  level: all
  folder: "./logs"

routes:
  - path: /*
    name: allServer
    strategy: round-robin
    max_nodes: 0 # this one doesn't seem like a good config value.
    health_timeout_ms: 500
    inactive_timeout_ms: 5000
    node_request_limit: 10
    docker:
      image: node-server
      internal_port: 3000
      request_scale_threshold: 150
      no_requests_timeout_ms: 5000
      initial_containers: 3
    servers:
    