server:
  port: 8080
  host: localhost

load_balancer:
  health_timeout: 5000
  max_nodes: 0
  strategy: round-robin

docker:
  docker_image: node-server
  internal_port: 3000

logging:
  level: all
  folder: "./logs"