name: 🔨 Fix
description: Report a bug or issue
title: "fix: <short description>"
labels: [bug, fix]
body:
  - type: textarea
    id: what
    attributes:
      label: What is the issue?
      description: Describe the issue or bug in detail.
    validations:
      required: true

  - type: textarea
    id: how
    attributes:
      label: How can we reproduce the issue?
      description: Provide steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What is the expected behavior?
      description: Describe what you expected to happen.
    validations:
      required: true