server:
  port: 8080
  host: localhost

logging:
  level: none
  folder: "./logs"

emitter:
  enabled: false
  path: "/events"

routes:
  - path: /*
    name: allServer
    strategy: round-robin
    health_timeout_ms: 500
    node_request_limit: 100
    docker:
      image: node-server
      internal_port: 3000
      no_requests_timeout_ms: 5000
    pool:
      activation_interval_ms: 100
      inactive_size: 5
      active_size: 10
      max_active: 20
    servers:
    