server:
  port: 8080
  host: localhost

logging:
  level: all
  folder: "./logs"

emitter:
  enabled: true
  path: "/events"

routes:
  - path: /*
    name: allServer
    strategy: round-robin
    health_timeout_ms: 500
    node_request_limit: 5
    docker:
      image: node-server
      internal_port: 3000
      no_requests_timeout_ms: 5000
    pool:
      inactive_size: 3
      active_size: 2
    servers:
    