server:
  port: 8080
  host: localhost

logging:
  level: 2
  folder: "./logs"
  max_lines: 50000

emitter:
  enabled: false
  path: "/events"

routes:
  - path: /*
    name: allServer
    strategy: round-robin
    health_timeout_ms: 500
    route_queue_size: 50
    node_queue_size: 10
    worker_threads: 30
    docker:
      image: node-server
      internal_port: 3000
      no_requests_timeout_ms: 5000
    pool:
      activation_interval_ms: 100
      cleanup_interval_ms: 5000
      inactive_size: 2
      active_size: 2
      max_active: 20
    servers:
      # - url: http://localhost:3000
      #   weight: 1
      # - url: http://localhost:3001
      #   weight: 1