server:
  port: 8080
  host: localhost

logging:
  level: 2
  folder: "./logs"

emitter:
  enabled: false
  path: "/events"

routes:
  - path: /*
    name: allServer
    strategy: round-robin
    health_timeout_ms: 500
    route_queue_size: 150
    node_queue_size: 100
    docker:
      image: node-server
      internal_port: 3000
      no_requests_timeout_ms: 5000
    pool:
      activation_interval_ms: 100
      cleanup_interval_ms: 5000
      inactive_size: 2
      active_size: 4
      max_active: 20
    servers:
    
